credentials       = "./key/onyx-hangout-411709-309b6dab16d6.json"
project           = "onyx-hangout-411709"
region            = "us-central1"
location          = "US"
bq_dataset_name   = "zoomcamp_mage_dataset"
gcs_bucket_name   = "terraform-zoomcamp_wk2"
gcs_storage_class = "STANDARD"